[package]
name = "rawsocket_helper"
version = "0.1.0"
authors = ["wugifer <wugifer@>"]
edition = "2018"
description = "use rawsocket"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wugifer/rawsocket-helper"
documentation = "https://docs.rs/rawsocket-helper/"


[dependencies]
